# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x417dwo_4Y6492ipWJXE6UBT0aH6Tqrp

# Preprocessing
"""

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
from google.colab import drive
import os

import torch.nn as nn
from torchvision import models

import torch.optim as optim
from tqdm.auto import tqdm

drive.mount('/content/drive')

data_dir = '/content/drive/MyDrive/animals'

train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

full_dataset = datasets.ImageFolder(root=data_dir)

train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size
train_data, val_data = random_split(full_dataset, [train_size, val_size])

train_data.dataset.transform = train_transforms
val_data.dataset.transform = val_transforms

train_loader = DataLoader(train_data, batch_size=16, shuffle=True)
val_loader = DataLoader(val_data, batch_size=16, shuffle=False)

print(f"Classes found: {full_dataset.classes}")
print(f"Training samples: {len(train_data)}")

"""# Model Training"""

import torch.nn as nn
from torchvision import models

num_classes = len(full_dataset.classes)

model = models.resnet18(weights='IMAGENET1K_V1')

for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Linear(model.fc.in_features, num_classes)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

print(f"Model loaded and moved to {device}")

"""# Training Loop"""

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.001) # Only train the new head
epochs = 10

for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    # Create a progress bar for the training loader
    train_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [Train]", unit="batch")

    for inputs, labels in train_bar:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # Statistics
        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        # Update the progress bar suffix with live stats
        train_bar.set_postfix(loss=running_loss/len(train_loader), acc=f"{100.*correct/total:.2f}%")

    # 3. Validation Phase
    model.eval()
    val_correct = 0
    val_total = 0

    # Create a progress bar for the validation loader
    val_bar = tqdm(val_loader, desc=f"Epoch {epoch+1}/{epochs} [Val]", unit="batch", leave=False)

    with torch.no_grad():
        for inputs, labels in val_bar:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, predicted = outputs.max(1)
            val_total += labels.size(0)
            val_correct += predicted.eq(labels).sum().item()

            val_bar.set_postfix(val_acc=f"{100.*val_correct/val_total:.2f}%")

    print(f"--- Epoch {epoch+1} Summary: Train Acc: {100.*correct/total:.2f}% | Val Acc: {100.*val_correct/val_total:.2f}% ---")

print("Training Complete!")

"""Saving the Model"""

from google.colab import drive
import torch
import os

# Define save path in Drive
save_dir = '/content/drive/MyDrive/models'
os.makedirs(save_dir, exist_ok=True)

model_path = os.path.join(save_dir, 'model.pth')

# Save the model
torch.save({
    'epoch': epochs,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
}, model_path)

print(f"Model saved to {model_path}")

"""Testing the model"""

from google.colab import drive
import torch
import torchvision.transforms as transforms
import torchvision.models as models
import torch.nn as nn
from PIL import Image

drive.mount('/content/drive')

# ── 1. Recreate the exact same architecture ────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class_names = ['antelope', 'badger', 'bat', 'bear', 'bee', 'beetle', 'bison', 'boar', 'butterfly', 'cat', 'caterpillar', 'chimpanzee', 'cockroach', 'cow', 'coyote', 'crab', 'crow', 'deer', 'dog', 'dolphin', 'donkey', 'dragonfly', 'duck', 'eagle', 'elephant', 'flamingo', 'fly', 'fox', 'goat', 'goldfish', 'goose', 'gorilla', 'grasshopper', 'hamster', 'hare', 'hedgehog', 'hippopotamus', 'hornbill', 'horse', 'hummingbird', 'hyena', 'jellyfish', 'kangaroo', 'koala', 'ladybugs', 'leopard', 'lion', 'lizard', 'lobster', 'mosquito', 'moth', 'mouse', 'octopus', 'okapi', 'orangutan', 'otter', 'owl', 'ox', 'oyster', 'panda', 'parrot', 'pelecaniformes', 'penguin', 'pig', 'pigeon', 'porcupine', 'possum', 'raccoon', 'rat', 'reindeer', 'rhinoceros', 'sandpiper', 'seahorse', 'seal', 'shark', 'sheep', 'snake', 'sparrow', 'squid', 'squirrel', 'starfish', 'swan', 'tiger', 'turkey', 'turtle', 'whale', 'wolf', 'wombat', 'woodpecker', 'zebra']  # ⚠️ Replace with your actual classes
                                            # Check what was printed: "Classes found: [...]"
num_classes = len(class_names)

model = models.resnet18(weights=None)
model.fc = nn.Linear(model.fc.in_features, num_classes)  # must match training

# ── 2. Load your saved checkpoint ─────────────────────────────────────────────
model_path = '/content/drive/MyDrive/models/model.pth'
checkpoint = torch.load(model_path, map_location=device)
model.load_state_dict(checkpoint['model_state_dict'])

model.to(device)
model.eval()
print("✅ Model loaded successfully!")

# ── 3. Same transforms as your val_transforms ─────────────────────────────────
predict_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# ── 4. Prediction function ─────────────────────────────────────────────────────
def predict(image_path):
    img = Image.open(image_path).convert('RGB')
    tensor = predict_transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(tensor)
        probs = torch.softmax(outputs, dim=1)[0]
        predicted_idx = probs.argmax().item()
        confidence = probs[predicted_idx].item()

    print(f"\n🖼️  Image      : {image_path}")
    print(f"🏆 Prediction : {class_names[predicted_idx]}")
    print(f"📊 Confidence : {confidence*100:.2f}%")

    return class_names[predicted_idx], confidence

# ── 5. Run predictions ─────────────────────────────────────────────────────────

# Multiple images
image_paths = [
    '/content/drive/MyDrive/animals/1Tests/shark.jpg',
    '/content/drive/MyDrive/animals/1Tests/bear.jpg'
]
for path in image_paths:
    predict(path)
